# Generated by Django 5.1.3 on 2024-11-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='test',
            new_name='text',
        ),
    ]
